nome = input('Qual seu nome?')
print('Eae {}, deixa eu te falar, tú tá lindão ein.'.format(nome))
dia = int(input('você nasceu em que dia do mês?'))
mês = int(input('Você nasceu em qual mês?'))
ano = int(input('Você é de qual ano?'))
resposta = input('Então seu nome é {} e você nasceu na data de {}/{}/{}?'.format(nome,dia,mês,ano))